// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto-demo/protobuf/rpc.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BookSearchRequest) Reset() {
	*x = BookSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demo_protobuf_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSearchRequest) ProtoMessage() {}

func (x *BookSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_protobuf_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSearchRequest.ProtoReflect.Descriptor instead.
func (*BookSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_protobuf_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *BookSearchRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookSearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BookSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book      *BookInfo  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Publisher *Publisher `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *BookSearchResponse) Reset() {
	*x = BookSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demo_protobuf_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSearchResponse) ProtoMessage() {}

func (x *BookSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_protobuf_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSearchResponse.ProtoReflect.Descriptor instead.
func (*BookSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_protobuf_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *BookSearchResponse) GetBook() *BookInfo {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *BookSearchResponse) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

var File_proto_demo_protobuf_rpc_proto protoreflect.FileDescriptor

var file_proto_demo_protobuf_rpc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x64, 0x65, 0x6d, 0x6f, 0x1a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x11, 0x42,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x67, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x2d,
	0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x32, 0x4c, 0x0a,
	0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6d, 0x74, 0x73, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x72, 0x75,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_demo_protobuf_rpc_proto_rawDescOnce sync.Once
	file_proto_demo_protobuf_rpc_proto_rawDescData = file_proto_demo_protobuf_rpc_proto_rawDesc
)

func file_proto_demo_protobuf_rpc_proto_rawDescGZIP() []byte {
	file_proto_demo_protobuf_rpc_proto_rawDescOnce.Do(func() {
		file_proto_demo_protobuf_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_demo_protobuf_rpc_proto_rawDescData)
	})
	return file_proto_demo_protobuf_rpc_proto_rawDescData
}

var file_proto_demo_protobuf_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_demo_protobuf_rpc_proto_goTypes = []interface{}{
	(*BookSearchRequest)(nil),  // 0: demo.BookSearchRequest
	(*BookSearchResponse)(nil), // 1: demo.BookSearchResponse
	(*BookInfo)(nil),           // 2: demo.BookInfo
	(*Publisher)(nil),          // 3: demo.Publisher
}
var file_proto_demo_protobuf_rpc_proto_depIdxs = []int32{
	2, // 0: demo.BookSearchResponse.book:type_name -> demo.BookInfo
	3, // 1: demo.BookSearchResponse.publisher:type_name -> demo.Publisher
	0, // 2: demo.SearchService.Search:input_type -> demo.BookSearchRequest
	1, // 3: demo.SearchService.Search:output_type -> demo.BookSearchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_demo_protobuf_rpc_proto_init() }
func file_proto_demo_protobuf_rpc_proto_init() {
	if File_proto_demo_protobuf_rpc_proto != nil {
		return
	}
	file_proto_demo_protobuf_books_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_demo_protobuf_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_demo_protobuf_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_demo_protobuf_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demo_protobuf_rpc_proto_goTypes,
		DependencyIndexes: file_proto_demo_protobuf_rpc_proto_depIdxs,
		MessageInfos:      file_proto_demo_protobuf_rpc_proto_msgTypes,
	}.Build()
	File_proto_demo_protobuf_rpc_proto = out.File
	file_proto_demo_protobuf_rpc_proto_rawDesc = nil
	file_proto_demo_protobuf_rpc_proto_goTypes = nil
	file_proto_demo_protobuf_rpc_proto_depIdxs = nil
}
